http://192.168.218.168:8080/sign/lvzym2070/428930198009203823/18810230936/32000/12/0x6eff8e3db86afe6dbcde6c10b81fbce7b7d6b88e77516d1ba644816a21e76868/Los/30/3/自住/0x431c9b7c0496a5fabefe52ec0a50f2c01a1bf5b2/0x5507a83808f6515e06aae83fbca97ae2a1bec0d350cdfb5e3f8ba69f5a48f083

CREATE TABLE `house_transaction_record` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userid` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '房东手机号',
  `addr` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '房东地址',
  `leaser_id` varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '租客手机号',
  `leaser_addr` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '租客地址',
  `house_addr` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '地址',
  `tenancy` int(11) NOT NULL DEFAULT '0' COMMENT '租期',
  `rental` int(11) NOT NULL DEFAULT '0' COMMENT '真实租金',
  `house_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '房屋hash',
  `tx_hash` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '交易Hash',
  `house_use` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '房屋用途',
  `state` int(11) NOT NULL DEFAULT '0' COMMENT '状态',
  `rent_start_time` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '租赁开始时间',
  `rent_end_time` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '租赁结束时间',
  `pay_deadline` int DEFAULT '0' COMMENT '交付期限',
  `pay_one` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '维护方',
  `renewal_before_moneth` int DEFAULT '0' COMMENT '续租提前时间',
  `renewal_landlord_moneth` int DEFAULT '0' COMMENT '甲方书面回复时间',
  `notice_break_moneth` int DEFAULT '0' COMMENT '双方提前终止通知时间',
  `landlord_break_moneth` int DEFAULT '0' COMMENT '甲方提前终止时间',
  `falsify_year` int DEFAULT '0' COMMENT '年度违约赔偿额度',
  `flsify_month` int DEFAULT '0' COMMENT '日违约金',
  `agree_copies` int DEFAULT '0' COMMENT '合同份数',
  `landlord_sign_time` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '甲方签订时间',
  `lease_sign_time` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '乙方签订时间',
  `createtime` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '创建时间',
  `updatetime` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;